import numpy as np

from evaluation.stage1_figures import NAMES, WALSH


def test_walsh_coordinates_recover_tripartite_phase():
    # Basis phases generated by theta * ZZZ have signs (-1)^(a+b+c).
    theta = 0.37
    phases = np.asarray([theta, -theta, -theta, theta, -theta, theta, theta, -theta])
    coordinates = phases @ WALSH.T
    recovered = dict(zip(NAMES, coordinates))
    assert np.isclose(recovered["ABC"], theta)
    for name in ("A", "B", "C", "AB", "AC", "BC"):
        assert np.isclose(recovered[name], 0.0)
