from __future__ import annotations

import math
from dataclasses import dataclass

import torch


@dataclass(frozen=True)
class FourierPulseBounds:
    basis_size: int
    max_field_uT: float
    min_angular_frequency: float
    max_angular_frequency: float
    phase_bound: float
    taper_fraction: float = 0.15

    @property
    def component_amplitude_bound(self) -> float:
        # Each Fourier coefficient may be as large as the physical field bound.
        # The sampled waveform is globally rescaled below only when its actual
        # peak exceeds max_field_uT. This retains cancellation between terms and
        # is compatible with the published parameter vectors.
        return self.max_field_uT

    @property
    def n_parameters(self) -> int:
        return 3 * self.basis_size


@dataclass(frozen=True)
class WaveformFitResult:
    raw: torch.Tensor
    relative_error: float
    initial_relative_error: float
    peak_fraction: float


def tukey_window(time_grid: torch.Tensor, taper_fraction: float) -> torch.Tensor:
    """Differentiable flat-top cosine taper with zero endpoints."""
    if time_grid.ndim != 1 or time_grid.numel() < 2:
        raise ValueError("time_grid must be one-dimensional with at least two points.")
    if not 0.0 < taper_fraction <= 0.5:
        raise ValueError("taper_fraction must lie in (0, 0.5].")

    t0 = time_grid[0]
    duration = time_grid[-1] - t0
    if duration <= 0:
        raise ValueError("time_grid must be strictly increasing.")
    x = (time_grid - t0) / duration
    alpha = torch.as_tensor(taper_fraction, dtype=x.dtype, device=x.device)

    ramp_up = 0.5 * (1.0 - torch.cos(math.pi * x / alpha))
    ramp_down = 0.5 * (1.0 - torch.cos(math.pi * (1.0 - x) / alpha))
    window = torch.where(x < alpha, ramp_up, torch.ones_like(x))
    window = torch.where(x > 1.0 - alpha, ramp_down, window)
    return window


def _safe_atanh(x: torch.Tensor, eps: float = 1.0e-7) -> torch.Tensor:
    return torch.atanh(torch.clamp(x, -1.0 + eps, 1.0 - eps))


def _safe_logit(x: torch.Tensor, eps: float = 1.0e-7) -> torch.Tensor:
    x = torch.clamp(x, eps, 1.0 - eps)
    return torch.log(x) - torch.log1p(-x)


class BoundedFourierPulse:
    """
    Smooth bounded Fourier pulse.

    The optimizer works with unconstrained raw parameters. Physical amplitudes,
    frequencies and phases are generated by smooth transformations, so Adam and
    LBFGS never cross a hard parameter boundary.
    """

    def __init__(self, bounds: FourierPulseBounds):
        self.bounds = bounds

    def unpack_raw(self, raw: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        if raw.ndim != 1 or raw.numel() != self.bounds.n_parameters:
            raise ValueError(
                f"Expected {self.bounds.n_parameters} raw parameters, got {tuple(raw.shape)}."
            )
        n = self.bounds.basis_size
        raw_a, raw_w, raw_p = raw[:n], raw[n : 2 * n], raw[2 * n :]

        amplitudes = self.bounds.component_amplitude_bound * torch.tanh(raw_a)
        w_min = self.bounds.min_angular_frequency
        w_max = self.bounds.max_angular_frequency
        frequencies = w_min + (w_max - w_min) * torch.sigmoid(raw_w)
        phases = self.bounds.phase_bound * torch.tanh(raw_p)
        return amplitudes, frequencies, phases

    def physical_vector(self, raw: torch.Tensor) -> torch.Tensor:
        amplitudes, frequencies, phases = self.unpack_raw(raw)
        return torch.cat((amplitudes, frequencies, phases))

    def raw_from_physical(self, physical: torch.Tensor) -> torch.Tensor:
        physical = torch.as_tensor(physical, dtype=torch.float64)
        if physical.ndim != 1 or physical.numel() != self.bounds.n_parameters:
            raise ValueError(
                f"Expected {self.bounds.n_parameters} physical parameters, "
                f"got {tuple(physical.shape)}."
            )
        n = self.bounds.basis_size
        amplitudes = physical[:n]
        frequencies = physical[n : 2 * n]
        phases = physical[2 * n :]

        raw_a = _safe_atanh(amplitudes / self.bounds.component_amplitude_bound)
        scaled_w = (
            (frequencies - self.bounds.min_angular_frequency)
            / (self.bounds.max_angular_frequency - self.bounds.min_angular_frequency)
        )
        raw_w = _safe_logit(scaled_w)

        wrapped_phases = torch.remainder(phases + math.pi, 2.0 * math.pi) - math.pi
        raw_p = _safe_atanh(wrapped_phases / self.bounds.phase_bound)
        return torch.cat((raw_a, raw_w, raw_p))

    def initial_raw(
        self,
        *,
        device: torch.device | str,
        dtype: torch.dtype = torch.float64,
        generator: torch.Generator | None = None,
    ) -> torch.Tensor:
        n = self.bounds.basis_size
        raw_a = 0.08 * torch.randn(n, dtype=dtype, device=device, generator=generator)
        frequencies = torch.linspace(
            self.bounds.min_angular_frequency,
            self.bounds.max_angular_frequency,
            n + 2,
            dtype=dtype,
            device=device,
        )[1:-1]
        scaled_w = (
            (frequencies - self.bounds.min_angular_frequency)
            / (self.bounds.max_angular_frequency - self.bounds.min_angular_frequency)
        )
        raw_w = _safe_logit(scaled_w)
        raw_p = 0.05 * torch.randn(n, dtype=dtype, device=device, generator=generator)
        return torch.cat((raw_a, raw_w, raw_p))

    def drive(self, time_grid: torch.Tensor, raw: torch.Tensor) -> torch.Tensor:
        amplitudes, frequencies, phases = self.unpack_raw(raw)
        phase_matrix = frequencies[:, None] * time_grid[None, :] + phases[:, None]
        carrier_sum = torch.sum(amplitudes[:, None] * torch.cos(phase_matrix), dim=0)
        unconstrained = tukey_window(time_grid, self.bounds.taper_fraction) * carrier_sum
        peak = torch.amax(torch.abs(unconstrained))
        scale = torch.clamp(peak / self.bounds.max_field_uT, min=1.0)
        return unconstrained / scale

    def controls(self, time_grid: torch.Tensor, raw: torch.Tensor) -> list[torch.Tensor]:
        mw = self.drive(time_grid, raw)
        rf = torch.zeros_like(mw)
        return [mw, rf]

    def regularization(self, mw_drive: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        scale = max(self.bounds.max_field_uT, torch.finfo(mw_drive.dtype).tiny)
        normalized = mw_drive / scale
        fluence = torch.mean(normalized.square())
        smoothness = torch.mean((normalized[1:] - normalized[:-1]).square())
        return fluence, smoothness

    def peak_penalty(self, mw_drive: torch.Tensor) -> torch.Tensor:
        """Squared relative violation of the configured sampled peak field."""
        peak_fraction = torch.amax(torch.abs(mw_drive)) / self.bounds.max_field_uT
        return torch.relu(peak_fraction - 1.0).square()

    def _fft_initial_raw(self, time_grid: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
        """Deterministic dense-frequency matching-pursuit initialization.

        The historical name is retained for checkpoint compatibility, but the
        implementation is stronger than a plain FFT peak pick.  It selects one
        cosine/sine frequency pair at a time from a dense grid and re-solves all
        linear coefficients after every selection.  This is robust to the
        smooth envelope and to nominally nonuniform float32 checkpoint grids.
        """
        n = self.bounds.basis_size
        differences = time_grid[1:] - time_grid[:-1]
        if torch.any(differences <= 0):
            raise ValueError("Saved waveform time grid must be strictly increasing.")

        lower = max(0.0, self.bounds.min_angular_frequency)
        upper = max(
            abs(self.bounds.min_angular_frequency),
            abs(self.bounds.max_angular_frequency),
        )
        if upper <= lower:
            raise ValueError("The configured frequency interval is empty.")

        grid_size = max(1001, 100 * n)
        frequency_grid = torch.linspace(
            lower,
            upper,
            grid_size,
            dtype=target.dtype,
            device=target.device,
        )
        window = tukey_window(time_grid, self.bounds.taper_fraction)
        residual = target.detach().clone()
        available = torch.ones(grid_size, dtype=torch.bool, device=target.device)
        selected: list[int] = []
        duration = float((time_grid[-1] - time_grid[0]).detach().cpu())
        minimum_separation = 0.10 * 2.0 * math.pi / duration
        coefficients = None

        for _ in range(n):
            best_score = -math.inf
            best_index = 0
            for start in range(0, grid_size, 128):
                frequencies = frequency_grid[start : start + 128]
                cos_columns = window[:, None] * torch.cos(
                    time_grid[:, None] * frequencies[None, :]
                )
                sin_columns = window[:, None] * torch.sin(
                    time_grid[:, None] * frequencies[None, :]
                )
                cos_norm = cos_columns.square().sum(dim=0).clamp_min(1.0e-30)
                sin_norm = sin_columns.square().sum(dim=0).clamp_min(1.0e-30)
                scores = (
                    (cos_columns.T @ residual).square() / cos_norm
                    + (sin_columns.T @ residual).square() / sin_norm
                )
                scores = torch.where(
                    available[start : start + frequencies.numel()],
                    scores,
                    torch.full_like(scores, -math.inf),
                )
                value, local_index = torch.max(scores, dim=0)
                if float(value.detach().cpu()) > best_score:
                    best_score = float(value.detach().cpu())
                    best_index = start + int(local_index.detach().cpu())

            selected.append(best_index)
            available &= (
                torch.abs(frequency_grid - frequency_grid[best_index])
                >= minimum_separation
            )
            selected_frequencies = frequency_grid[
                torch.as_tensor(selected, dtype=torch.long, device=target.device)
            ]
            cos_columns = window[:, None] * torch.cos(
                time_grid[:, None] * selected_frequencies[None, :]
            )
            sin_columns = window[:, None] * torch.sin(
                time_grid[:, None] * selected_frequencies[None, :]
            )
            design = torch.cat((cos_columns, sin_columns), dim=1)
            coefficients = torch.linalg.lstsq(
                design, target[:, None]
            ).solution[:, 0]
            residual = target - design @ coefficients

        assert coefficients is not None
        selected_frequencies = frequency_grid[
            torch.as_tensor(selected, dtype=torch.long, device=target.device)
        ]
        cos_coefficients = coefficients[:n]
        sin_coefficients = coefficients[n:]
        amplitudes = torch.sqrt(
            cos_coefficients.square() + sin_coefficients.square()
        )
        phases = torch.atan2(-sin_coefficients, cos_coefficients)

        amplitude_limit = self.bounds.component_amplitude_bound * (1.0 - 1.0e-6)
        amplitudes = torch.clamp(amplitudes, max=amplitude_limit)
        frequencies = torch.clamp(
            selected_frequencies,
            min=self.bounds.min_angular_frequency + 1.0e-6,
            max=self.bounds.max_angular_frequency - 1.0e-6,
        )
        phase_limit = self.bounds.phase_bound * (1.0 - 1.0e-6)
        phases = torch.clamp(phases, min=-phase_limit, max=phase_limit)
        order = torch.argsort(frequencies)
        return self.raw_from_physical(
            torch.cat((amplitudes[order], frequencies[order], phases[order]))
        ).to(device=target.device, dtype=target.dtype)

    def fit_to_waveform(
        self,
        time_grid: torch.Tensor,
        target: torch.Tensor,
        *,
        steps: int,
        learning_rate: float,
        gradient_clip_norm: float,
        initial_raw: torch.Tensor | None = None,
        restarts: int = 1,
        lbfgs_steps: int = 0,
        seed: int = 7,
        peak_penalty_weight: float = 10.0,
    ) -> WaveformFitResult:
        """Fit this pulse ansatz to a saved sampled waveform.

        Frequency optimization is non-convex.  The FFT/least-squares estimate is
        therefore supplemented by deterministic jittered restarts, followed by
        optional LBFGS polishing.  This fit is inexpensive compared with a gate
        propagation and is used only to generate a direct-Fourier warm start.
        """
        time_grid = torch.as_tensor(time_grid, dtype=torch.float64)
        target = torch.as_tensor(
            target, dtype=torch.float64, device=time_grid.device
        ).reshape(-1)
        if time_grid.shape != target.shape:
            raise ValueError("time_grid and target waveform must have the same shape.")
        if target.numel() < 3:
            raise ValueError("At least three waveform samples are required.")
        if restarts < 1:
            raise ValueError("restarts must be at least one.")

        spectral_raw = self._fft_initial_raw(time_grid, target).detach()
        normalization = torch.clamp(torch.mean(target.square()), min=1.0e-30)

        def fit_loss(parameter: torch.Tensor) -> torch.Tensor:
            reconstruction = self.drive(time_grid, parameter)
            mismatch = torch.mean((reconstruction - target).square()) / normalization
            return mismatch + peak_penalty_weight * self.peak_penalty(reconstruction)

        def relative_error(parameter: torch.Tensor) -> torch.Tensor:
            reconstruction = self.drive(time_grid, parameter)
            return torch.sqrt(
                torch.mean((reconstruction - target).square()) / normalization
            )

        candidates: list[torch.Tensor] = [spectral_raw]
        if initial_raw is not None:
            candidate = torch.as_tensor(
                initial_raw, dtype=target.dtype, device=target.device
            ).reshape(-1)
            if candidate.numel() == self.bounds.n_parameters:
                candidates.append(candidate.detach())

        generator = torch.Generator(device=target.device)
        generator.manual_seed(seed)
        n = self.bounds.basis_size
        while len(candidates) < restarts:
            candidate = spectral_raw.clone()
            candidate[:n] += 0.10 * torch.randn(
                n, dtype=target.dtype, device=target.device, generator=generator
            )
            candidate[n : 2 * n] += 0.35 * torch.randn(
                n, dtype=target.dtype, device=target.device, generator=generator
            )
            candidate[2 * n :] += 0.35 * torch.randn(
                n, dtype=target.dtype, device=target.device, generator=generator
            )
            candidates.append(candidate)

        with torch.no_grad():
            initial_errors = [float(relative_error(item).cpu()) for item in candidates]
        initial_error = min(initial_errors)
        best_raw = candidates[min(range(len(candidates)), key=initial_errors.__getitem__)].clone()
        best_objective = math.inf
        best_error = initial_error

        for candidate in candidates:
            raw = candidate.detach().clone().requires_grad_(True)
            optimizer = torch.optim.Adam([raw], lr=learning_rate)
            local_best_raw = raw.detach().clone()
            with torch.no_grad():
                local_best_objective = float(fit_loss(raw).cpu())

            for _ in range(max(0, steps)):
                optimizer.zero_grad(set_to_none=True)
                loss = fit_loss(raw)
                loss.backward()
                if gradient_clip_norm > 0:
                    torch.nn.utils.clip_grad_norm_([raw], gradient_clip_norm)
                optimizer.step()
                with torch.no_grad():
                    value = float(fit_loss(raw).cpu())
                    if value < local_best_objective:
                        local_best_objective = value
                        local_best_raw = raw.detach().clone()

            if local_best_objective < best_objective:
                best_objective = local_best_objective
                best_raw = local_best_raw
                with torch.no_grad():
                    best_error = float(relative_error(best_raw).cpu())

        if lbfgs_steps > 0:
            raw = best_raw.detach().clone().requires_grad_(True)
            optimizer = torch.optim.LBFGS(
                [raw],
                max_iter=lbfgs_steps,
                history_size=min(50, max(10, lbfgs_steps)),
                tolerance_grad=1.0e-12,
                tolerance_change=1.0e-15,
                line_search_fn="strong_wolfe",
            )
            lbfgs_best_raw = best_raw.detach().clone()
            lbfgs_best_objective = best_objective

            def closure() -> torch.Tensor:
                nonlocal lbfgs_best_raw, lbfgs_best_objective
                optimizer.zero_grad(set_to_none=True)
                loss = fit_loss(raw)
                loss.backward()
                with torch.no_grad():
                    value = float(loss.cpu())
                    if value < lbfgs_best_objective:
                        lbfgs_best_objective = value
                        lbfgs_best_raw = raw.detach().clone()
                return loss

            optimizer.step(closure)
            best_raw = lbfgs_best_raw
            with torch.no_grad():
                best_error = float(relative_error(best_raw).cpu())

        with torch.no_grad():
            peak_fraction = float(
                (
                    self.drive(time_grid, best_raw).abs().max()
                    / self.bounds.max_field_uT
                ).cpu()
            )
        return WaveformFitResult(
            raw=best_raw,
            relative_error=best_error,
            initial_relative_error=initial_error,
            peak_fraction=peak_fraction,
        )


class DirectFourierPulse(BoundedFourierPulse):
    """Literal manuscript pulse: window times one finite Fourier sum.

    Unlike :class:`BoundedFourierPulse`, this class applies no sampled clipping,
    rescaling, reference waveform, or output nonlinearity.  Consequently the
    physical parameter vector written to the checkpoint reconstructs the saved
    drive exactly through the manuscript equation.  The total-field limit is
    enforced by the differentiable peak-violation term in the objective.
    """

    def drive(self, time_grid: torch.Tensor, raw: torch.Tensor) -> torch.Tensor:
        amplitudes, frequencies, phases = self.unpack_raw(raw)
        phase_matrix = frequencies[:, None] * time_grid[None, :] + phases[:, None]
        carrier_sum = torch.sum(
            amplitudes[:, None] * torch.cos(phase_matrix), dim=0
        )
        return tukey_window(time_grid, self.bounds.taper_fraction) * carrier_sum

def linear_interpolate_1d(
    reference_time: torch.Tensor,
    reference_values: torch.Tensor,
    query_time: torch.Tensor,
) -> torch.Tensor:
    """Piecewise-linear interpolation implemented with PyTorch operations.

    The reference arrays are constants during control optimization, while the
    query grid is fixed for each optimizer stage. Keeping the interpolation in
    torch avoids an unnecessary CPU round trip and preserves device placement.
    """
    reference_time = torch.as_tensor(
        reference_time, dtype=query_time.dtype, device=query_time.device
    ).reshape(-1)
    reference_values = torch.as_tensor(
        reference_values, dtype=query_time.dtype, device=query_time.device
    ).reshape(-1)
    if reference_time.shape != reference_values.shape:
        raise ValueError("reference_time and reference_values must have equal shapes.")
    if reference_time.numel() < 2:
        raise ValueError("At least two reference samples are required.")
    if torch.any(reference_time[1:] <= reference_time[:-1]):
        raise ValueError("reference_time must be strictly increasing.")
    tolerance = max(
        1.0e-15,
        float(torch.abs(reference_time[-1] - reference_time[0]).detach().cpu())
        * 1.0e-9,
    )
    if query_time[0] < reference_time[0] - tolerance or query_time[-1] > reference_time[-1] + tolerance:
        raise ValueError("query_time lies outside the saved reference waveform interval.")

    clipped = torch.clamp(query_time, reference_time[0], reference_time[-1])
    upper = torch.searchsorted(reference_time, clipped, right=True)
    upper = torch.clamp(upper, 1, reference_time.numel() - 1)
    lower = upper - 1
    t0 = reference_time[lower]
    t1 = reference_time[upper]
    y0 = reference_values[lower]
    y1 = reference_values[upper]
    weight = (clipped - t0) / (t1 - t0)
    return y0 + weight * (y1 - y0)


class ReferenceResidualPulse(BoundedFourierPulse):
    """Exact saved waveform plus a bounded differentiable Fourier correction.

    At the zero-correction parameter vector, the generated control is exactly
    the published waveform (up to interpolation onto the requested propagation
    grid). The residual is multiplied by the pointwise amplitude headroom, so
    the total microwave field cannot exceed ``max_field_uT``.
    """

    def __init__(
        self,
        bounds: FourierPulseBounds,
        reference_time_grid: torch.Tensor,
        reference_mw_drive: torch.Tensor,
    ):
        super().__init__(bounds)
        reference_time_grid = torch.as_tensor(
            reference_time_grid, dtype=torch.float64
        ).reshape(-1)
        reference_mw_drive = torch.as_tensor(
            reference_mw_drive, dtype=torch.float64
        ).reshape(-1)
        if reference_time_grid.shape != reference_mw_drive.shape:
            raise ValueError(
                "reference_time_grid and reference_mw_drive must have equal shapes."
            )
        if torch.any(reference_time_grid[1:] <= reference_time_grid[:-1]):
            raise ValueError("reference_time_grid must be strictly increasing.")
        peak = float(reference_mw_drive.abs().max())
        if peak > bounds.max_field_uT * (1.0 + 1.0e-8):
            raise ValueError(
                f"Saved reference peak {peak:.6g} exceeds configured field bound "
                f"{bounds.max_field_uT:.6g}. Increase max_rabi_mhz or inspect units."
            )
        self.reference_time_grid = reference_time_grid.detach().clone()
        self.reference_mw_drive = reference_mw_drive.detach().clone()

    def reference(self, time_grid: torch.Tensor) -> torch.Tensor:
        return linear_interpolate_1d(
            self.reference_time_grid, self.reference_mw_drive, time_grid
        )

    def initial_raw(
        self,
        *,
        device: torch.device | str,
        dtype: torch.dtype = torch.float64,
        generator: torch.Generator | None = None,
    ) -> torch.Tensor:
        del generator
        n = self.bounds.basis_size
        raw_a = torch.zeros(n, dtype=dtype, device=device)
        frequencies = torch.linspace(
            self.bounds.min_angular_frequency,
            self.bounds.max_angular_frequency,
            n + 2,
            dtype=dtype,
            device=device,
        )[1:-1]
        scaled_w = (
            (frequencies - self.bounds.min_angular_frequency)
            / (self.bounds.max_angular_frequency - self.bounds.min_angular_frequency)
        )
        raw_w = _safe_logit(scaled_w)
        raw_p = torch.zeros(n, dtype=dtype, device=device)
        return torch.cat((raw_a, raw_w, raw_p))

    def drive(self, time_grid: torch.Tensor, raw: torch.Tensor) -> torch.Tensor:
        reference = self.reference(time_grid)
        correction = super().drive(time_grid, raw)
        normalized_correction = correction / self.bounds.max_field_uT
        headroom = torch.clamp(
            self.bounds.max_field_uT - torch.abs(reference), min=0.0
        )
        return reference + headroom * torch.tanh(normalized_correction)


